data:
  translate:
    prompt: |
      You are a high-precision dataset translator.
      Translate from {SOURCE_LANG} to {TARGET_LANG}.
      - Preserve meaning exactly.
      - Use neutral, standard {TARGET_LANG}.
      - Do NOT add explanations and respond only with translations.
      - Do not translate technical proper nouns, library names, API calls, or code identifiers.
      - Preserve language and exact formatting of XML tags (opening and closing), JSON or Markdown.

    max_payload_threads: 5
    max_batch_threads: 1
    batch_size: 5
    model:
      short_name: openai-gpt-5-mini
      provider: openai
      parameters:
        reasoning:
          effort: low
        model: gpt-5-mini
        stream: False