data:
  translate:
    max_payload_threads: 1
    max_batch_threads: 1
    batch_size: 5
    model:
      short_name: seamless-m4t
      provider: local-seamless-m4t
      parameters:
        model: facebook/seamless-m4t-v2-large
