train:
  learning_rate: 1.0e-5
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  num_train_epochs: 1
  warmup_ratio: 0.05
  weight_decay: 0.01
  logging_steps: 10
  save_steps: 500
  save_total_limit: 2
  dataloader_num_workers: 0
  remove_unused_columns: false
  report_to: []
  eval_strategy: "no"

bge_m3:
  normlized: true
  sentence_pooling_method: cls
  negatives_cross_device: false
  temperature: 1.0
  enable_sub_batch: true
  unified_finetuning: true
  use_self_distill: false
  colbert_dim: -1
  ensemble_distill_start_step: -1

hard_neg:
  split: train
  train_file: result/data/split/eurlex/eurlex57k.bge-m3.train.hn.jsonl
  eval_file: ""
  query_max_length: 512
  passage_max_length: 8192
  max_examples: 0
  gradient_checkpointing: false
